CONTIKI_PROJECT = solarPro
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += 

CONTIKI_WITH_RIME = 1
CONTIKI = $(HOME)/contiki

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include
